# PIPE Configuration Template
# Generated by OpenTofu

environment: ${environment}

logging:
  level: ${log_level}
  format: json
  file: /var/log/pipe/pipe.log

state_dir: /var/lib/pipe/state

# OpenBao integration
secrets:
  provider: openbao
  address: http://openbao-system.svc.cluster.local:8200
  auth_method: kubernetes
  role: pipe-bot

# Zitadel IAM integration
identity:
  provider: zitadel
  issuer: https://zitadel-system.svc.cluster.local
  client_id_secret: openbao://secret/data/pipe/zitadel/client-id
  client_secret_secret: openbao://secret/data/pipe/zitadel/client-secret

# Container registry
registry:
  url: https://zot-registry.svc.cluster.local
  verify_signatures: true
  cosign_key_secret: openbao://secret/data/pipe/cosign/public-key

# Bot configurations
bots:
  pipeline:
    enabled: true
    check_interval: 30
    max_concurrent_pipelines: 10

  data_processor:
    enabled: true
    num_workers: 5
    queue_size: 1000
    status_interval: 30

  monitor:
    enabled: true
    monitor_interval: 60
    health_check_interval: 30
    silence_threshold_seconds: 300
    error_threshold: 10

  integration_hub:
    enabled: true
    max_connections: 100
    timeout_seconds: 30

# Governance configuration
governance:
  enabled: true

  # Domains in the ecosystem
  domains:
%{ for domain in domains ~}
    - ${domain}
%{ endfor ~}

  # Approval workflow
  approval:
    required_reviewers: 2
    auto_approve_timeout_hours: 72

  # Compliance
  compliance:
    categories:
      - integration_standards
      - quality_metrics
      - security_policy
      - data_governance
      - review_process

    check_interval: 3600

# Monitoring configuration
monitoring:
  prometheus:
    enabled: true
    port: 9090
    scrape_interval: 15s

  grafana:
    enabled: true
    port: 3000

  alertmanager:
    enabled: true
    port: 9093

# Network configuration
network:
  service_mesh: cilium
  encryption: true
  network_policies: strict

# Security
security:
  tls:
    enabled: true
    cert_secret: openbao://pki/issue/pipe/common_name=pipe.local

  rbac:
    enabled: true

  pod_security:
    enforce: restricted
